### ISSUE TITLE
where is folder mseg_semantic?

### ISSUE THREAD

**Issue by luoyuchenmlcv** [daniel-bogdoll/unknown_objects_roads#3]
Dear Daniel,
I am trying to run the code, but based on your suggestions in readme, it requires to navigate to mseg_semantic to perform inference.
But I cannot find this folder from your folder structure:
![image](https://user-images.githubusercontent.com/102636806/177551095-37994592-8cdc-4528-b612-c3fefa9a4ea8.png)

**Comment by daniel-bogdoll** [comment]
Thanks! @Christin95 do you know if this got lost during the transition to GitHub? I do see it in our internal repository. If it's still identical with the internal version, please let me know, then I'll push it here :)

**Comment by daniel-bogdoll** [comment]
@luoyuchenmlcv I have added the missing files, sorry for the inconveniences! Let me know, if you experience any others issues while running the code!
