### ISSUE TITLE
where is  results/detection_pred.pkl

### ISSUE THREAD

**Issue by CCBRR** [daniel-bogdoll/unknown_objects_roads#7]
where is results/detection_pred.pkl in Preprocessing, clustering and 3D-point cloud prediction
   what format the calibration calibration_file_path = calibration_path+'/{}.pkl'.format(filename)
why lidar and calibration is "pkl" no pcd,lidar format in waymo is pcd
thank you!

**Comment by daniel-bogdoll** [comment]
Could you please provide us with more concrete descriptions of what your issues are? :)

**Comment by CCBRR** [comment]
can you send me your premodel on waymo，i can't have enough gpu to train a model，the centerpoint maker doesn't send me the pre model after I sent him email

**Comment by daniel-bogdoll** [comment]
Unfortunately, we can't do that :)
