### ISSUE TITLE
how to prepare waymo dataset

### ISSUE THREAD

**Issue by chrisyan** [daniel-bogdoll/unknown_objects_roads#8]
Hi author,

thank you for your great work! Could you explain how to prepare waymo dataset? Specifically, in waymo_mapping_clean.py

camera_path = "/disk/vanishing_data/zl254/waymo_extraction_all/testing/camera"
lidar_path = "/disk/vanishing_data/zl254/waymo_extraction_all/testing/lidar"
calibration_path = "/disk/vanishing_data/zl254/waymo_extraction_calibration/testing/calibration"

where can I get those data?

Best,
Chris

**Comment by daniel-bogdoll** [comment]
Dear Chris, unfortunately we're not supporting this repository anymore. However, I have removed the local paths to reduce confusion.
